//
//  VideoCellControlsSheet.swift
//  ClaudeCollage
//
//  Step 04 slice 5b — the per-cell control panel, presented from the video editor
//  as a `UISheetPresentationController` sheet (the plan's slide-up panel). SwiftUI
//  is the right tool here: it's a form of toggles and sliders, no canvas gestures.
//
//  Carries the plan's per-cell controls: a frame thumbnail strip (generated by the
//  VC via `AVAssetImageGenerator`) as the visual reference for the in/out trim,
//  loop, mute, volume, transition, and replace/remove.
//
//  v1 deviation (documented): trim uses two bounded sliders over the thumbnail
//  strip rather than draggable pan handles on the strip itself — same capability,
//  far less custom gesture code. Draggable handles are a later refinement.
//

import SwiftUI

struct VideoCellControlsSheet: View {

    /// The editable snapshot of one cell — mirrors the mutable fields of
    /// `VideoCellState` so the sheet stays decoupled from the view model.
    struct Values: Equatable {
        var trimStart: Double
        var trimEnd: Double
        var isLooping: Bool
        var isMuted: Bool
        var volume: Double
        var transitionStyle: CellTransition.Style?
        var transitionDuration: Double
    }

    let cellNumber: Int
    /// Source duration in seconds; bounds the trim sliders.
    let duration: Double
    let thumbnails: [UIImage]

    @State private var values: Values

    let onChange: (Values) -> Void
    let onReplace: () -> Void
    let onRemove: () -> Void
    let onClose: () -> Void

    init(cellNumber: Int, duration: Double, thumbnails: [UIImage], values: Values,
         onChange: @escaping (Values) -> Void,
         onReplace: @escaping () -> Void,
         onRemove: @escaping () -> Void,
         onClose: @escaping () -> Void) {
        self.cellNumber = cellNumber
        self.duration = max(0.1, duration)
        self.thumbnails = thumbnails
        self._values = State(initialValue: values)
        self.onChange = onChange
        self.onReplace = onReplace
        self.onRemove = onRemove
        self.onClose = onClose
    }

    private let transitions: [(label: String, style: CellTransition.Style?)] = [
        ("None", nil),
        ("Fade", .crossfade),
        ("Slide ←", .slideLeft),
        ("Slide →", .slideRight),
        ("Zoom", .zoomIn),
    ]

    var body: some View {
        VStack(spacing: 0) {
            header
            ScrollView {
                VStack(alignment: .leading, spacing: 24) {
                    if !thumbnails.isEmpty { thumbnailStrip }
                    trimSection
                    playbackSection
                    audioSection
                    transitionSection
                    actions
                }
                .padding(20)
            }
        }
        .background(Color(Theme.Color.background).ignoresSafeArea())
    }

    // MARK: - Header

    private var header: some View {
        HStack {
            Button("Done", action: onClose)
                .accessibilityIdentifier("cellControlsDoneButton")
            Spacer()
            Text("Clip \(cellNumber)")
                .font(.headline)
                .foregroundStyle(Color(Theme.Color.textPrimary))
            Spacer()
            Button("Done") {}.opacity(0).accessibilityHidden(true)
        }
        .padding()
        .foregroundStyle(Color(Theme.Color.accent))
    }

    // MARK: - Thumbnails + trim

    private var thumbnailStrip: some View {
        ScrollView(.horizontal, showsIndicators: false) {
            HStack(spacing: 2) {
                ForEach(Array(thumbnails.enumerated()), id: \.offset) { _, image in
                    Image(uiImage: image)
                        .resizable()
                        .aspectRatio(contentMode: .fill)
                        .frame(width: 56, height: 56)
                        .clipped()
                }
            }
            .clipShape(RoundedRectangle(cornerRadius: 8))
        }
    }

    private var trimSection: some View {
        VStack(alignment: .leading, spacing: 10) {
            sectionTitle("Trim")
            HStack {
                Text("In \(timeLabel(values.trimStart))")
                Spacer()
                Text("Out \(timeLabel(values.trimEnd))")
            }
            .font(.caption)
            .foregroundStyle(Color(Theme.Color.textSecondary))

            Slider(value: Binding(
                get: { values.trimStart },
                set: { newValue in
                    values.trimStart = min(newValue, values.trimEnd - 0.1)
                    push()
                }), in: 0...duration)
                .accessibilityIdentifier("cellTrimStartSlider")

            Slider(value: Binding(
                get: { values.trimEnd },
                set: { newValue in
                    values.trimEnd = max(newValue, values.trimStart + 0.1)
                    push()
                }), in: 0...duration)
                .accessibilityIdentifier("cellTrimEndSlider")
        }
    }

    // MARK: - Playback / audio

    private var playbackSection: some View {
        Toggle("Loop to fill", isOn: Binding(
            get: { values.isLooping },
            set: { values.isLooping = $0; push() }))
            .accessibilityIdentifier("cellLoopToggle")
            .tint(Color(Theme.Color.accent))
            .foregroundStyle(Color(Theme.Color.textPrimary))
    }

    private var audioSection: some View {
        VStack(alignment: .leading, spacing: 10) {
            sectionTitle("Audio")
            Toggle("Mute", isOn: Binding(
                get: { values.isMuted },
                set: { values.isMuted = $0; push() }))
                .accessibilityIdentifier("cellMuteToggle")
                .tint(Color(Theme.Color.accent))
                .foregroundStyle(Color(Theme.Color.textPrimary))

            HStack {
                Image(systemName: "speaker.fill")
                Slider(value: Binding(
                    get: { values.volume },
                    set: { values.volume = $0; push() }), in: 0...1)
                    .accessibilityIdentifier("cellVolumeSlider")
                Image(systemName: "speaker.wave.3.fill")
            }
            .foregroundStyle(Color(Theme.Color.textSecondary))
            .disabled(values.isMuted)
            .opacity(values.isMuted ? 0.4 : 1)
        }
    }

    // MARK: - Transition

    private var transitionSection: some View {
        VStack(alignment: .leading, spacing: 10) {
            sectionTitle("Intro Transition")
            ScrollView(.horizontal, showsIndicators: false) {
                HStack(spacing: 10) {
                    ForEach(Array(transitions.enumerated()), id: \.offset) { _, item in
                        transitionChip(label: item.label, style: item.style)
                    }
                }
            }
            if values.transitionStyle != nil {
                Text("Duration \(String(format: "%.1fs", values.transitionDuration))")
                    .font(.caption)
                    .foregroundStyle(Color(Theme.Color.textSecondary))
                Slider(value: Binding(
                    get: { values.transitionDuration },
                    set: { values.transitionDuration = $0; push() }), in: 0.1...2.0)
                    .accessibilityIdentifier("cellTransitionDurationSlider")
            }
        }
    }

    private func transitionChip(label: String, style: CellTransition.Style?) -> some View {
        let selected = values.transitionStyle == style
        return Button {
            values.transitionStyle = style
            Haptics.tap()
            push()
        } label: {
            Text(label)
                .font(.caption)
                .foregroundStyle(selected ? Color(Theme.Color.textOnAccent)
                                          : Color(Theme.Color.textPrimary))
                .padding(.horizontal, 14)
                .padding(.vertical, 10)
                .background(selected ? Color(Theme.Color.accent) : Color(Theme.Color.surface))
                .clipShape(Capsule())
        }
        .buttonStyle(.plain)
        .accessibilityIdentifier("cellTransition-\(label)")
    }

    // MARK: - Actions

    private var actions: some View {
        VStack(spacing: 12) {
            Button(action: onReplace) {
                Label("Replace Video", systemImage: "arrow.triangle.2.circlepath")
                    .frame(maxWidth: .infinity)
                    .padding()
                    .background(Color(Theme.Color.surface))
                    .clipShape(RoundedRectangle(cornerRadius: 14))
            }
            .buttonStyle(.plain)
            .foregroundStyle(Color(Theme.Color.accent))
            .accessibilityIdentifier("cellReplaceButton")

            Button(action: onRemove) {
                Label("Remove Video", systemImage: "trash")
                    .frame(maxWidth: .infinity)
                    .padding()
                    .background(Color(Theme.Color.surface))
                    .clipShape(RoundedRectangle(cornerRadius: 14))
            }
            .buttonStyle(.plain)
            .foregroundStyle(.red)
            .accessibilityIdentifier("cellRemoveButton")
        }
    }

    // MARK: - Helpers

    private func sectionTitle(_ text: String) -> some View {
        Text(text.uppercased())
            .font(.caption)
            .foregroundStyle(Color(Theme.Color.textSecondary))
    }

    private func timeLabel(_ seconds: Double) -> String {
        String(format: "%.1fs", max(0, seconds))
    }

    private func push() { onChange(values) }
}
