//
//  VideoCellControlsSheet.swift
//  ClaudeCollage
//
//  Step 04 slice 5b — the per-cell control panel, presented from the video editor
//  as a `UISheetPresentationController` sheet (the plan's slide-up panel). SwiftUI
//  is the right tool here: it's a form of toggles and sliders, no canvas gestures.
//
//  Carries the plan's per-cell controls: a frame thumbnail strip (generated by the
//  VC via `AVAssetImageGenerator`) as the visual reference for the in/out trim,
//  loop, mute, volume, transition, and replace/remove.
//
//  v1 deviation (documented): trim uses two bounded sliders over the thumbnail
//  strip rather than draggable pan handles on the strip itself — same capability,
//  far less custom gesture code. Draggable handles are a later refinement.
//

import SwiftUI

struct VideoCellControlsSheet: View {

    /// The editable snapshot of one cell — mirrors the mutable fields of
    /// `VideoCellState` so the sheet stays decoupled from the view model.
    struct Values: Equatable {
        var trimStart: Double
        var trimEnd: Double
        var isLooping: Bool
        var isMuted: Bool
        var volume: Double
        var transitionStyle: CellTransition.Style?
        var transitionDuration: Double
    }

    let cellNumber: Int
    /// Source duration in seconds; bounds the trim sliders.
    let duration: Double
    let thumbnails: [UIImage]

    @State private var values: Values

    /// Fired continuously while a slider is dragged — live preview, no undo step.
    let onLiveChange: (Values) -> Void
    /// Fired at the end of a drag or on a discrete change (toggle / chip) — records
    /// one undo step for the whole gesture.
    let onCommit: (Values) -> Void
    let onReplace: () -> Void
    let onRemove: () -> Void
    let onClose: () -> Void

    init(cellNumber: Int, duration: Double, thumbnails: [UIImage], values: Values,
         onLiveChange: @escaping (Values) -> Void,
         onCommit: @escaping (Values) -> Void,
         onReplace: @escaping () -> Void,
         onRemove: @escaping () -> Void,
         onClose: @escaping () -> Void) {
        self.cellNumber = cellNumber
        self.duration = max(0.1, duration)
        self.thumbnails = thumbnails
        self._values = State(initialValue: values)
        self.onLiveChange = onLiveChange
        self.onCommit = onCommit
        self.onReplace = onReplace
        self.onRemove = onRemove
        self.onClose = onClose
    }

    private let transitions: [(label: String, style: CellTransition.Style?)] = [
        ("None", nil),
        ("Fade", .crossfade),
        ("Slide ←", .slideLeft),
        ("Slide →", .slideRight),
        ("Zoom", .zoomIn),
    ]

    var body: some View {
        VStack(spacing: 0) {
            header
            ScrollView {
                VStack(alignment: .leading, spacing: 24) {
                    trimSection
                    playbackSection
                    audioSection
                    transitionSection
                    actions
                }
                .padding(20)
            }
        }
        .background(Color(Theme.Color.background).ignoresSafeArea())
    }

    // MARK: - Header

    private var header: some View {
        HStack {
            Button("Done", action: onClose)
                .accessibilityIdentifier("cellControlsDoneButton")
            Spacer()
            Text("Clip \(cellNumber)")
                .font(.themeHeadline)
                .foregroundStyle(Color(Theme.Color.textPrimary))
            Spacer()
            Button("Done") {}.opacity(0).accessibilityHidden(true)
        }
        .padding()
        .foregroundStyle(Color(Theme.Color.accent))
    }

    // MARK: - Trim (filmstrip + draggable handles)

    private var trimSection: some View {
        VStack(alignment: .leading, spacing: 10) {
            sectionTitle("Trim")
            HStack {
                Text("In \(timeLabel(values.trimStart))")
                Spacer()
                Text("Out \(timeLabel(values.trimEnd))")
            }
            .font(.themeCaption)
            .foregroundStyle(Color(Theme.Color.textSecondary))

            TrimStrip(
                thumbnails: thumbnails,
                duration: duration,
                trimStart: Binding(get: { values.trimStart }, set: { values.trimStart = $0 }),
                trimEnd: Binding(get: { values.trimEnd }, set: { values.trimEnd = $0 }),
                onLive: { onLiveChange(values) },
                onCommit: { onCommit(values) })
        }
    }

    // MARK: - Playback / audio

    private var playbackSection: some View {
        Toggle("Loop to fill", isOn: Binding(
            get: { values.isLooping },
            set: { values.isLooping = $0; onCommit(values) }))
            .accessibilityIdentifier("cellLoopToggle")
            .tint(Color(Theme.Color.accent))
            .foregroundStyle(Color(Theme.Color.textPrimary))
    }

    private var audioSection: some View {
        VStack(alignment: .leading, spacing: 10) {
            sectionTitle("Audio")
            Toggle("Mute", isOn: Binding(
                get: { values.isMuted },
                set: { values.isMuted = $0; onCommit(values) }))
                .accessibilityIdentifier("cellMuteToggle")
                .tint(Color(Theme.Color.accent))
                .foregroundStyle(Color(Theme.Color.textPrimary))

            HStack {
                Image(systemName: "speaker.fill")
                Slider(value: Binding(
                    get: { values.volume },
                    set: { values.volume = $0; onLiveChange(values) }),
                    in: 0...1, onEditingChanged: commitOnRelease)
                    .accessibilityIdentifier("cellVolumeSlider")
                Image(systemName: "speaker.wave.3.fill")
            }
            .foregroundStyle(Color(Theme.Color.textSecondary))
            .disabled(values.isMuted)
            .opacity(values.isMuted ? 0.4 : 1)
        }
    }

    // MARK: - Transition

    private var transitionSection: some View {
        VStack(alignment: .leading, spacing: 10) {
            sectionTitle("Intro Transition")
            ScrollView(.horizontal, showsIndicators: false) {
                HStack(spacing: 10) {
                    ForEach(Array(transitions.enumerated()), id: \.offset) { _, item in
                        transitionChip(label: item.label, style: item.style)
                    }
                }
            }
            if values.transitionStyle != nil {
                Text("Duration \(String(format: "%.1fs", values.transitionDuration))")
                    .font(.themeCaption)
                    .foregroundStyle(Color(Theme.Color.textSecondary))
                Slider(value: Binding(
                    get: { values.transitionDuration },
                    set: { values.transitionDuration = $0; onLiveChange(values) }),
                    in: 0.1...2.0, onEditingChanged: commitOnRelease)
                    .accessibilityIdentifier("cellTransitionDurationSlider")
            }
        }
    }

    private func transitionChip(label: String, style: CellTransition.Style?) -> some View {
        let selected = values.transitionStyle == style
        return Button {
            values.transitionStyle = style
            Haptics.tap()
            onCommit(values)
        } label: {
            Text(label)
                .font(.themeCaption)
                .foregroundStyle(selected ? Color(Theme.Color.textOnAccent)
                                          : Color(Theme.Color.textPrimary))
                .padding(.horizontal, 14)
                .padding(.vertical, 10)
                .background(selected ? Color(Theme.Color.accent) : Color(Theme.Color.surface))
                .clipShape(Capsule())
        }
        .buttonStyle(.plain)
        .accessibilityIdentifier("cellTransition-\(label)")
    }

    // MARK: - Actions

    private var actions: some View {
        VStack(spacing: 12) {
            Button(action: onReplace) {
                Label("Replace Video", systemImage: "arrow.triangle.2.circlepath")
                    .frame(maxWidth: .infinity)
                    .padding()
                    .background(Color(Theme.Color.surface))
                    .clipShape(RoundedRectangle(cornerRadius: 14))
            }
            .buttonStyle(.plain)
            .foregroundStyle(Color(Theme.Color.accent))
            .accessibilityIdentifier("cellReplaceButton")

            Button(action: onRemove) {
                Label("Remove Video", systemImage: "trash")
                    .frame(maxWidth: .infinity)
                    .padding()
                    .background(Color(Theme.Color.surface))
                    .clipShape(RoundedRectangle(cornerRadius: 14))
            }
            .buttonStyle(.plain)
            .foregroundStyle(.red)
            .accessibilityIdentifier("cellRemoveButton")
        }
    }

    // MARK: - Helpers

    private func sectionTitle(_ text: String) -> some View {
        Text(text.uppercased())
            .font(.themeCaption)
            .foregroundStyle(Color(Theme.Color.textSecondary))
    }

    private func timeLabel(_ seconds: Double) -> String {
        String(format: "%.1fs", max(0, seconds))
    }

    /// Slider `onEditingChanged`: commit once when the drag ends.
    private func commitOnRelease(_ editing: Bool) {
        if !editing { onCommit(values) }
    }
}

// MARK: - Filmstrip with draggable trim handles

/// The CapCut/InShot-style trim control: a frame filmstrip with a left and right
/// handle you drag to set the in/out points. The area outside the selection dims;
/// the selection carries an accent frame. Dragging fires `onLive` continuously and
/// `onCommit` on release (one undo step).
private struct TrimStrip: View {

    let thumbnails: [UIImage]
    let duration: Double
    @Binding var trimStart: Double
    @Binding var trimEnd: Double
    let onLive: () -> Void
    let onCommit: () -> Void

    private let handleWidth: CGFloat = 16
    private let height: CGFloat = 60
    private let minGap: Double = 0.1

    var body: some View {
        GeometryReader { geo in
            let width = geo.size.width
            let startX = xFor(trimStart, width: width)
            let endX = xFor(trimEnd, width: width)

            ZStack(alignment: .leading) {
                filmstrip
                    .frame(width: width, height: height)
                    .clipShape(RoundedRectangle(cornerRadius: 8))

                // Dim the trimmed-away regions.
                Color.black.opacity(0.55).frame(width: max(0, startX))
                Color.black.opacity(0.55).frame(width: max(0, width - endX)).offset(x: endX)

                // Selection frame.
                RoundedRectangle(cornerRadius: 4)
                    .stroke(Color(Theme.Color.accent), lineWidth: 3)
                    .frame(width: max(0, endX - startX), height: height)
                    .offset(x: startX)

                handle.offset(x: startX - handleWidth / 2)
                    .gesture(drag(isStart: true, width: width))
                    .accessibilityIdentifier("cellTrimStartHandle")
                handle.offset(x: endX - handleWidth / 2)
                    .gesture(drag(isStart: false, width: width))
                    .accessibilityIdentifier("cellTrimEndHandle")
            }
            .frame(height: height)
        }
        .frame(height: height)
    }

    private var filmstrip: some View {
        HStack(spacing: 0) {
            if thumbnails.isEmpty {
                Rectangle().fill(Color(Theme.Color.controlFill))
            } else {
                ForEach(Array(thumbnails.enumerated()), id: \.offset) { _, image in
                    Image(uiImage: image)
                        .resizable()
                        .aspectRatio(contentMode: .fill)
                        .frame(maxWidth: .infinity)
                        .frame(height: height)
                        .clipped()
                }
            }
        }
    }

    private var handle: some View {
        RoundedRectangle(cornerRadius: 4)
            .fill(Color(Theme.Color.accent))
            .frame(width: handleWidth, height: height)
            .overlay(
                Capsule().fill(.white).frame(width: 3, height: height * 0.35))
    }

    private func xFor(_ seconds: Double, width: CGFloat) -> CGFloat {
        guard duration > 0 else { return 0 }
        return CGFloat(min(1, max(0, seconds / duration))) * width
    }

    private func drag(isStart: Bool, width: CGFloat) -> some Gesture {
        DragGesture(minimumDistance: 0)
            .onChanged { value in
                guard width > 0 else { return }
                let seconds = Double(min(width, max(0, value.location.x)) / width) * duration
                if isStart {
                    trimStart = min(seconds, trimEnd - minGap)
                } else {
                    trimEnd = max(seconds, trimStart + minGap)
                }
                onLive()
            }
            .onEnded { _ in onCommit() }
    }
}
