//
//  AppIconTests.swift
//  CaroullageTests
//
//  Step 05b Part A.
//
//  The app icon is generated by `Tools/IconGenerator/main.swift` into
//  `Caroullage/Resources/Assets.xcassets`. No Swift code references it, so a
//  renamed asset, a lost asset catalog or a dropped
//  `ASSETCATALOG_COMPILER_APPICON_NAME` would ship a blank icon while every
//  other test stayed green — which is precisely the state the app was in until
//  this step: the build setting was there, the catalog was not.
//
//  `CFBundleIcons` is absent from the source `Info.plist`; actool injects it at
//  build time from the appiconset. Asserting on it therefore checks the whole
//  chain — catalog present, named correctly, and actually compiled in.
//

import UIKit
import XCTest

final class AppIconTests: XCTestCase {

    private var primaryIcon: [String: Any] {
        get throws {
            let icons = try XCTUnwrap(
                Bundle.main.object(forInfoDictionaryKey: "CFBundleIcons") as? [String: Any],
                "No CFBundleIcons in the built Info.plist — the asset catalog did not compile in."
            )
            return try XCTUnwrap(icons["CFBundlePrimaryIcon"] as? [String: Any])
        }
    }

    func testAppIconIsCompiledIntoTheBundle() throws {
        let name = try XCTUnwrap(primaryIcon["CFBundleIconName"] as? String)
        XCTAssertEqual(name, "AppIcon", "The primary icon must be the AppIcon appiconset.")
    }

    func testAppIconImageLoadsAndIsSquare() throws {
        let files = try XCTUnwrap(primaryIcon["CFBundleIconFiles"] as? [String])
        XCTAssertFalse(files.isEmpty, "actool produced no icon files.")

        let icon = try XCTUnwrap(UIImage(named: try XCTUnwrap(files.first)))
        XCTAssertEqual(icon.size.width, icon.size.height, "App icons must be square.")
        XCTAssertGreaterThanOrEqual(icon.size.width, 60)
    }

    /// The default appearance must be fully opaque. App Review rejects a
    /// marketing icon with transparency, and a see-through icon on the home
    /// screen looks like a bug rather than a design. The dark and tinted
    /// appearances are deliberately transparent, but they are not what
    /// `CFBundleIconFiles` points at.
    func testDefaultAppearanceIsOpaque() throws {
        let files = try XCTUnwrap(primaryIcon["CFBundleIconFiles"] as? [String])
        let icon = try XCTUnwrap(UIImage(named: try XCTUnwrap(files.first)))
        let cgImage = try XCTUnwrap(icon.cgImage)

        let width = cgImage.width
        let height = cgImage.height
        var pixels = [UInt8](repeating: 0, count: width * height * 4)
        let context = try XCTUnwrap(CGContext(
            data: &pixels,
            width: width, height: height,
            bitsPerComponent: 8, bytesPerRow: width * 4,
            space: CGColorSpaceCreateDeviceRGB(),
            bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
        ))
        context.draw(cgImage, in: CGRect(x: 0, y: 0, width: width, height: height))

        // Sampling a grid rather than every pixel: a transparent icon is
        // transparent in swathes, never in one stray pixel, and this keeps the
        // test instant.
        for row in stride(from: 0, to: height, by: max(1, height / 8)) {
            for column in stride(from: 0, to: width, by: max(1, width / 8)) {
                let alpha = pixels[(row * width + column) * 4 + 3]
                XCTAssertEqual(
                    alpha, 255,
                    "Icon pixel (\(column), \(row)) is not opaque (alpha \(alpha))."
                )
            }
        }
    }
}
